version: '3'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - ./api/_logs:/app/_logs
  mongodb:
    image: 'mongo:3.0.15'
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db